### ISSUE TITLE
DynamicAudioNormalizer makes some parts of audio quieter

### ISSUE THREAD

**Issue by knopp** [lordmulder/DynamicAudioNormalizer#15]
I'm not sure if this is intentional, but it is quite unexpected. I have peek value set to 0.7. In some loud sections of the audio MDynamicAudioNormalizer_PrivateData::getMaxLocalGain returns value less that 1, which results in audio volume actually being lowered compared to original. If I clamp the result to always be >= 1 it works as expected.

All my options: frame-length: 300, filter-size: 11, peek-value: 0.7, max-amplification: 5.0, target-rms: 0, compress-factor: 0, channel-coupling: 1, dc-correction: 0, alt-boundary: 1

**Comment by knopp** [comment]
Thanks. getMaxLocalGain was maybe not the right place to look at, however the amplificationFactor in amplifyFrame is still less than 1 in one of the videos I tested. That means the frame volume is lower after normalization than before.

**Comment by lordmulder** [comment]
> getMaxLocalGain was maybe not the right place to look at, however the amplificationFactor in amplifyFrame is still less than 1 in one of the videos I tested. That means the frame volume is lower after normalization than before.

Yes, that's perfectly possible – depending on how you have chosen the _target peak magnitude_ **and** depending on the neighboring frames. What I wrote above should make clear why that is 😏

**Comment by knopp** [comment]
Thank you for the explanation. I guess I my expectation was wrong. For some reason I assumed that the hitting the target peak magnitude would prevent frame from being amplified, but would not cause the frame actually ending up quieter than before normalisation. I simply treated target-peak magnitude as limit for amplification for quiet passages and did not expect the normalizer to touch loud passages. Maybe in future these limits could be separated?

**Comment by lordmulder** [comment]
> I simply treated target-peak magnitude as limit for amplification for quiet passages

That is pretty much what `maxAmplification` does. Isn't it?

> Maybe in future these limits could be separated?

I'm not sure what would be the justification for that...

**Comment by knopp** [comment]
Well, unlike target-peak magnitude, maxAmplification does not take frame loudness into account. So for some parts max amplification of 5 may be fine, for other it may be too much. So I wanted to use the peak magnitude to limit the amplification in some parts of the audio, but I didn't want this to affect scenes that are originally above my selected target-peak. If this not something that would be generally useful I'll be more than happy to just patch my local build :)

**Comment by lordmulder** [comment]
Well, the _**target peak magnitude**_ is the maximum magnitude (limit) that will ever be allowed - anything above that is considered as "clipping". So, if you don't want existing peaks in your input to be attenuated, you must set _target peak magnitude_ sufficiently high. At the same time, the _**max. amplification factor**_ can be sued to prevent "quiet" sections from being amplified too much. This is useful, IMO, because amplifying "quiet" sections by a very large factor can result in the quantization noise to become audible...
