### ISSUE TITLE
File formats + Details + Wrong encoding

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [lordmulder/DynamicAudioNormalizer#16]
I have a m4a file that I want to normalize. DAN cannot work with m4a as it doesn't know what it is. 

1. Which format I can use codec copy with ffmpeg with works with DAN?
1. Also, what does a WAV-File have to look like to be an input for DAN - Frequency, endian, resolution...?
1. Why are mp3-files huge that DAN outputs and how to minimize them?

**Comment by lordmulder** [comment]
DynamicAudioNormalizer CLI supports different input/output modules. These are:
- [libsndfile](http://www.mega-nerd.com/libsndfile/)
- [libmpg123](https://www.mpg123.de/)
- [libopusfile](https://github.com/xiph/opusfile)

So, as **input**, you can open all the various file types supported by *libsndfile* (which includes Wave Audio files as well as FLAC and Vorbis) plus MP3 files (will be decoded via *libmpg123*) plus Opus files (will be decoded via *libopusfile*). As far as *uncompressed* (PCM) Wave Audio files are concerned, pretty much ***all*** bit-depths, endianesses and sampling rates should be supported, as *libsndfile* handles that transparently for us. Wave Audio files containing "a-law", "µ-law" or "ADPCM" date should work as well, again via *libsndfile*.

Supported **output** formats include Wave Audio, FLAC and Ogg/Vorbis. We do ***not*** currently support MP3 *output*, as we do ***not*** include any kind of MP3 encoder library.
