### ISSUE TITLE
How to run/build it under Raspberry Pi

### ISSUE THREAD

**Issue by Bardo-Konrad** [lordmulder/DynamicAudioNormalizer#20]
This is the details

PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

It's an armv6l

I tried compiling it from source, yet it - even after modifications - crashed with Architecture is not supported!.

Any ideas how to build it there?

**Comment by lordmulder** [comment]
Raspberry Pi is not a target platform that was ever tested by me 😨 

(I don't have an ARM device)

Anyway, it would be interesting to know where exactly you get the "Architecture is not supported!" error. During the build? At runtime? And what exactly has been modified for what reason?

Best Regards
MuldeR
