### ISSUE TITLE
How to set up VST plugin on linux

### ISSUE THREAD

**Issue by JayC777-VO** [lordmulder/DynamicAudioNormalizer#21]
Setting up the plugin for Windows is explained well.  Haven't been able to figure it out for Mint Linux.

**Comment by lordmulder** [comment]
AFAIK, **VST** is a Windows-only technology :anguished:

There seems to be some efforts going on to get VST working on Linux, but I have never tried this and can **not** guarantee it will work for you. See here for some information (unfortunately German only):
* https://wiki.ubuntuusers.de/VST/
* https://www.linux-community.de/ausgaben/linuxuser/2005/06/vst-audio-plugins-in-linux-abspielen/

I think on Linux you will probably be better off by using the [**CLI program**](https://github.com/lordmulder/DynamicAudioNormalizer#command-line-usage) of DynAudNorm. Either that, or use FFmpeg (or anything based on FFmpeg), which has the DynAudNorm filter integrated now:
https://ffmpeg.org/ffmpeg-filters.html#dynaudnorm

Regards.
