### ISSUE TITLE
[Feature Request] Exclude breathing sounds

### ISSUE THREAD

**Issue by Bardo-Konrad** [lordmulder/DynamicAudioNormalizer#22]
I use it to normalize podcasts. Content-unaware as it is, it amplifies breathing sounds aswell.

I want you to make it exclude breathing sounds from normalization.

**Comment by lordmulder** [comment]
Unfortunately this is **way** out of scope for DynamicAudioNormalizer.

If some specialized plugin exists, that can suppress "breathing sounds", you may want to use this as a pre-processor *before* applying the DynamicAudioNormalizer. I'm not aware of such plugin though. But I would be surprised if it doesn't exist...

(not necessarily free though)

Regards.

-------------------------

BTW: https://streamgeeks.us/removing-breath-sounds-from-your-podcast/
