### ISSUE TITLE
Can't load the VST plugin into EqualizerAPO (how to fix that).

### ISSUE THREAD

**Issue by avc1657** [lordmulder/DynamicAudioNormalizer#27]
The error:
![Editor_HmPM2TBu8z](https://user-images.githubusercontent.com/68762165/158885969-87c09ffc-a058-40e3-bd79-30bb4b980ed0.jpg)

**Comment by lordmulder** [comment]
It appears your "host" application requires 64-Bit (x64) VST modules, but you were trying to load the 32-Bit (x86) one.
