### ISSUE TITLE
source download quirky

### ISSUE THREAD

**Issue by jimlynnjulian** [lordmulder/DynamicAudioNormalizer#28]
Clicked for  a download of "master.zip" source code, but nothing happened. Tried several times.
Right-clicked for  "Save as..." menu and that worked.

**Comment by lordmulder** [comment]
Well, I'm not a GitHub developer. Probably you want to report GitHub issues at:
https://support.github.com/contact/bug-report

Having said that, the easiest way is probably to just _clone_ the repository using [Git](https://git-scm.com/).

Either that, or:
![grafik](https://user-images.githubusercontent.com/470590/178341075-10e3266c-ee8b-4553-b22c-7189f40793da.png)

**Comment by jimlynnjulian** [comment]
Just for the record, This is the page I dealt with. Other sites were no problem.
If this is not an issue for you, this is not an issue for me. Have a good one.
