### ISSUE TITLE
ERROR: cp: cannot stat ‘DynamicAudioNormalizerCLI/bin/DynamicAudioNormalizerCLI’

### ISSUE THREAD

**Issue by peter1000** [lordmulder/DynamicAudioNormalizer#4]
Hi,

just to let you know that with your last [commit 0dfbba884e493843d8a118810cf77e6e2f671af6](https://github.com/lordmulder/DynamicAudioNormalizer/commit/0dfbba884e493843d8a118810cf77e6e2f671af6) you seem to have introduced an error.

Arch Linux

```
[STR] bin/DynamicAudioNormalizerCLI.bin
strip --strip-unneeded -o bin/DynamicAudioNormalizerCLI.bin bin/DynamicAudioNormalizerCLI-DBG.bin
make[1]: Leaving directory '/0_ARCH_TMP_BUILD_FOLDER_0/makepkg/dynamic-audio-normalizer-git_p/src/DynamicAudioNormalizer/DynamicAudioNormalizerCLI'

-----------------------------------------------------------------------------
Copy Binaries
-----------------------------------------------------------------------------

rm -rf ./bin/2015-07-20 
mkdir -p ./bin/2015-07-20/include
cp DynamicAudioNormalizerCLI/bin/DynamicAudioNormalizerCLI ./bin/2015-07-20
cp: cannot stat ‘DynamicAudioNormalizerCLI/bin/DynamicAudioNormalizerCLI’: No such file or directory
Makefile:154: recipe for target 'CopyAllBinaries' failed
make: *** [CopyAllBinaries] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

I checked and the previous commit works fine.

Cheers
P

**Comment by lordmulder** [comment]
Sorry, this is pretty much work in progress. I will (hopefully) fix 
Linux build tonight.

Regards,
MuldeR

**Comment by peter1000** [comment]
no problem just wanted to let you know.

**Comment by lordmulder** [comment]
Should be fixed by now:
0fcdb0fe05d2f75af4776fb53b33f3620815e9d6

**Comment by peter1000** [comment]
Thanks.

just compiled it with my [arch linux package](https://github.com/peter1000/ArchLinux_packages_p/tree/master/dynamic-audio-normalizer-git_p) and saw that the executables are now renamed to: **.bin** `DynamicAudioNormalizerCLI.bin`

Is that on purpose? - don't see that much on linux executable except for java self extracting binary file for Linux.

**Comment by lordmulder** [comment]
Yes. I recently added MinGW support to the Makefiles and we need to append `.exe` extension on Windows. For the sake of simplicity, `.bin` is appended on Linux.

**Comment by peter1000** [comment]
thanks
