### ISSUE TITLE
Support W64 format in sox

### ISSUE THREAD

**Issue by belonesox** [lordmulder/DynamicAudioNormalizer#7]
Please, add "W64" format support to your sox build.

(Regular cygwin sox support it
"AUDIO FILE FORMATS: 8svx aif aifc aiff aiffc al amb amr-nb amr-wb anb au avr awb caf cdda cdr cvs cvsd cvu dat dvms f32 f4 f64 f8 fap flac fssd gsm gsrt hcom htk ima ircam la lpc lpc10 lu mat mat4 mat5 maud mp2 mp3 nist ogg paf prc pvf raw s1 s16 s2 s24 s3 s32 s4 s8 sb sd2 sds sf sl sln smp snd sndfile sndr sndt sou sox sph sw txw u1 u16 u2 u24 u3 u32 u4 u8 ub ul uw vms voc vorbis vox w64 wav wavpcm wv wve xa xi") but your build, unfortunately no. 

(Audio files in my workflow in W64)

**Comment by lordmulder** [comment]
I think **SoX** needs to be built with *libsndfile* extra lib to support WAVE64.

Maybe I will try to build with libsndfile next time.

In the meantime, you can try [**FFmpeg**](https://ffmpeg.zeranoe.com/builds/), which should support WAVE64 as well...

**Comment by lordmulder** [comment]
For v2.10 release I have built Win32 binary of SoX with _libsndfile_ and thus W64 support.
