### ISSUE TITLE
Build from source code

### ISSUE THREAD

**Issue by sarbjit-longia** [lordmulder/DynamicAudioNormalizer#8]
I am trying to build the library from source code but could not. I tried running z_build.bat but it refers to folder ../Prerequisites which does not exists. 

Can you please give some instructions as how to build this library.

**Comment by lordmulder** [comment]
Hello,

the "Prerequisites" directory is for 3rd-party libraries and tools that 
are *not* part of my library. You either need to provide the 3rd-party 
libraries and tools yourself, or you can have a look at my Prerequisites 
package:

https://sourceforge.net/projects/muldersoft/files/Prerequisites/

Regards,
MuldeR
